version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "store"
s3_bucket = "s3-product-longldb"
s3_prefix = "store"
region = "us-east-2"
capabilities = "CAPABILITY_NAMED_IAM"
image_repositories = []
